### ISSUE TITLE
Content-Security-Policy-Report

### ISSUE THREAD

**Issue by Soean** [GoogleChromeLabs/wp-reporting-api#5]
## Issue Overview
The plugin sets the `Content-Security-Policy-Report-Only` header to `default-src https:;`. This means every inline style/script is being reported to the API. 

I know "[Inline code is considered harmful](https://developers.google.com/web/fundamentals/security/csp/#inline_code_is_considered_harmful)", but a lot of plugins are using wp_head or wp_footer to add styles and scripts. WordPress Core uses Inline CSS for the Styles defined in the customizer. There is no Core support in WP for script-src nonce. So there should be a way to allow inline scripts without being reported.

**Comment by swissspidy** [comment]
> There is no Core support in WP for script-src nonce

Relevant core tickets:

* https://core.trac.wordpress.org/ticket/39941
* https://core.trac.wordpress.org/ticket/32067
